---
#-------------------------------------------------#
#              Project Description                #
#-------------------------------------------------#
name: viteach_learning_app
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1
environment:
  sdk: ">=3.4.1 <4.0.0"

#-------------------------------------------------#
#                   Packages                      #
#-------------------------------------------------#
dependencies:
  animated_toggle_switch: ^0.8.2
  badges: ^2.0.2
  cached_network_image: ^3.3.1
  carousel_slider: ^4.2.1
  cupertino_icons: ^1.0.6
  flashy_tab_bar2: ^0.0.10
  flutter:
    sdk: flutter
  flutter_markdown: ^0.6.10
  flutter_native_splash: ^2.4.0
  flutter_svg: ^2.0.10+1
  get: ^4.6.6
  get_storage: ^2.1.1
  go_router: ^14.1.4
  google_fonts: ^6.2.1
  http: ^1.2.1
  iconsax: ^0.0.8
  image_cropper: ^7.0.5
  image_picker: ^1.1.2
  in_app_review: ^2.0.9
  intl: ^0.19.0
  liquid_pull_to_refresh: ^3.0.1
  percent_indicator: ^4.0.1
  provider: ^6.1.2
  shared_preferences: ^2.2.3
  shimmer: ^3.0.0
  smooth_page_indicator: ^1.1.0
  syncfusion_flutter_pdfviewer: ^25.2.7
  upgrader: ^10.3.0
  url_launcher: ^6.3.0
  flutter_html: ^3.0.0-beta.2

#-------------------------------------------------#
#                  Dev Packages                   #
#-------------------------------------------------#
dev_dependencies:
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/logos/play_store_512.png"

flutter:
  uses-material-design: true

  #-------------------------------------------------#
  #                 Local Assets                    #
  #-------------------------------------------------#
  assets:
    - assets/images/OnboardingImages/
    - assets/
    - assets/images/
    - assets/logos/

  #-------------------------------------------------#
  #                  Local Fonts                    #
  #-------------------------------------------------#
  fonts:
    - family: Rubik
      fonts:
        - asset: assets/fonts/Rubik-Light.ttf
          weight: 300
        - asset: assets/fonts/Rubik-Regular.ttf
          weight: 400
        - asset: assets/fonts/Rubik-Italic.ttf
          style: italic
        - asset: assets/fonts/Rubik-Medium.ttf
          weight: 500
        - asset: assets/fonts/Rubik-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/Rubik-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Rubik-Bold.ttf
          weight: 800
