#-------------------------------------------------#
#              Project Description                #
#-------------------------------------------------#
name: viteach_learning_app
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: '>=3.4.1 <4.0.0'






#-------------------------------------------------#
#                   Packages                      #
#-------------------------------------------------#
dependencies:
  flutter:
    sdk: flutter

  # Icons
  cupertino_icons: ^1.0.6
  iconsax: ^0.0.8






#-------------------------------------------------#
#                  Dev Packages                   #
#-------------------------------------------------#
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true






#-------------------------------------------------#
#                 Local Assets                    #
#-------------------------------------------------#
  assets:
    - assets/icons/
    - assets/images/
    - assets/logos/






#-------------------------------------------------#
#                  Local Fonts                    #
#-------------------------------------------------#
  fonts:
    - family: Rubik
      fonts:
        - asset: assets/fonts/Rubik-Light.ttf
          weight: 300
        - asset: assets/fonts/Rubik-Regular.ttf
          weight: 400
        - asset: assets/fonts/Rubik-Italic.ttf
          style: italic
        - asset: assets/fonts/Rubik-Medium.ttf
          weight: 500
        - asset: assets/fonts/Rubik-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/Rubik-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Rubik-Bold.ttf
          weight: 800