import 'dart:convert';
import 'package:http/http.dart' as http;
import 'package:viteach_learning_app/api/secret_keys.dart';
import 'package:viteach_learning_app/widgets/quote_api.dart';

class Api{
  static const base_url = "https://api.api-ninjas.com/v1/quotes?category=inspirational";

  static Future<Autogenerated> fetchRandomQuote() async {
    final response = await http.get(Uri.parse(base_url), headers: {'X-Api-Key': keys});
    if(response.statusCode == 200){
      final data = json.decode(response.body);
      return Autogenerated.fromJson(data[0]);
    }
    else{
    throw Exception("Failed to generate a quote");
    }
}
}
